/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import controller.admin_window.CreateAccountButtonController;
import controller.admin_window.FindAccountsButtonController;
import controller.admin_window.LogOutButtonController;
import controller.admin_window.RemoveAccountButtonController;
import controller.admin_window.UpdateAccountButtonController;
import javax.swing.JOptionPane;

/**
 *
 * @author Sandu
 */
public class AdminWindow extends javax.swing.JFrame {

    /**
     * Creates new form AdminWindow
     */
    public AdminWindow() {
        super("Dharmapala Maha Vidyala");
        initComponents();
        postInit();
    }

    public void postInit(){
        CreateAccountButtonController createAccountButtonController = new CreateAccountButtonController(this);
        create_account_button.addActionListener(createAccountButtonController);
        
        UpdateAccountButtonController updateAccountButtonController = new UpdateAccountButtonController(this);
        update_account_button.addActionListener(updateAccountButtonController);
        
        RemoveAccountButtonController removeAccountButtonController = new RemoveAccountButtonController(this);
        remove_account_button.addActionListener(removeAccountButtonController);
        
        FindAccountsButtonController findAccountsButtonController = new FindAccountsButtonController();
        find_accounts_button.addActionListener(findAccountsButtonController);
        
        LogOutButtonController logOutButtonController = new LogOutButtonController(this);
        logout_button.addActionListener(logOutButtonController);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        create_account_button = new javax.swing.JButton();
        update_account_button = new javax.swing.JButton();
        remove_account_button = new javax.swing.JButton();
        logout_button = new javax.swing.JButton();
        find_accounts_button = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(750, 450));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(null);

        create_account_button.setFont(new java.awt.Font("Trajan Pro", 1, 18)); // NOI18N
        create_account_button.setText("Create Account");
        jPanel1.add(create_account_button);
        create_account_button.setBounds(90, 30, 270, 50);

        update_account_button.setFont(new java.awt.Font("Trajan Pro", 1, 18)); // NOI18N
        update_account_button.setText("Update Account");
        jPanel1.add(update_account_button);
        update_account_button.setBounds(90, 100, 270, 50);

        remove_account_button.setFont(new java.awt.Font("Trajan Pro", 1, 18)); // NOI18N
        remove_account_button.setText("Remove Account");
        jPanel1.add(remove_account_button);
        remove_account_button.setBounds(90, 260, 270, 50);

        logout_button.setFont(new java.awt.Font("Trajan Pro", 1, 18)); // NOI18N
        logout_button.setText("Log Out");
        logout_button.setPreferredSize(new java.awt.Dimension(119, 50));
        jPanel1.add(logout_button);
        logout_button.setBounds(90, 340, 270, 50);

        find_accounts_button.setFont(new java.awt.Font("Trajan Pro", 1, 18)); // NOI18N
        find_accounts_button.setText("Find Accounts");
        find_accounts_button.setPreferredSize(new java.awt.Dimension(127, 50));
        jPanel1.add(find_accounts_button);
        find_accounts_button.setBounds(90, 180, 270, 50);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 750, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 430, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void start() {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AdminWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AdminWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AdminWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AdminWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                AdminWindow adminWindow = new AdminWindow();
                adminWindow.setVisible(true);
                adminWindow.setLocationRelativeTo(null);
                adminWindow.setResizable(false);
                adminWindow.addWindowListener(new java.awt.event.WindowAdapter(){
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent windowEvent) {
                        int showConfirmDialog = JOptionPane.showConfirmDialog(null, 
                                "Do you want to exit","Exit",
                                JOptionPane.YES_NO_OPTION);
                        
                        if(showConfirmDialog == JOptionPane.YES_OPTION){
                            System.exit(0);
                        }
                    }
                });
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton create_account_button;
    private javax.swing.JButton find_accounts_button;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton logout_button;
    private javax.swing.JButton remove_account_button;
    private javax.swing.JButton update_account_button;
    // End of variables declaration//GEN-END:variables
}
