/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import controller.create_account_window.CreateButtonController;
import javax.swing.JPasswordField;
import javax.swing.JTextField;

/**
 *
 * @author Sandu
 */
public class CreateAccountWindow extends javax.swing.JFrame {
    private static CreateAccountWindow createWindow = new CreateAccountWindow();
    /**
     * Creates new form CreateAccountWindow
     */
    private CreateAccountWindow() {
        super("Dharmapala Maha Vidyala");
        initComponents();
        postInit();
    }

    public void postInit(){
        CreateButtonController createAccountButtonController = new CreateButtonController(this);
        cretae_button.addActionListener(createAccountButtonController);
        
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        username_field = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        password_field = new javax.swing.JPasswordField();
        confirm_password_field = new javax.swing.JPasswordField();
        cretae_button = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        holder_name_field = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(750, 450));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(null);

        jLabel1.setFont(new java.awt.Font("Trajan Pro", 0, 16)); // NOI18N
        jLabel1.setText("User Name");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(100, 40, 160, 40);

        username_field.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jPanel1.add(username_field);
        username_field.setBounds(340, 40, 320, 40);

        jLabel2.setFont(new java.awt.Font("Trajan Pro", 0, 16)); // NOI18N
        jLabel2.setText("Password");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(100, 180, 180, 40);

        jLabel3.setFont(new java.awt.Font("Trajan Pro", 0, 16)); // NOI18N
        jLabel3.setText("Confirm Password");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(100, 260, 230, 40);

        password_field.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jPanel1.add(password_field);
        password_field.setBounds(340, 180, 320, 40);

        confirm_password_field.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jPanel1.add(confirm_password_field);
        confirm_password_field.setBounds(340, 260, 320, 40);

        cretae_button.setFont(new java.awt.Font("Trajan Pro", 0, 18)); // NOI18N
        cretae_button.setText("Create");
        jPanel1.add(cretae_button);
        cretae_button.setBounds(460, 330, 200, 50);

        jLabel4.setFont(new java.awt.Font("Trajan Pro", 0, 16)); // NOI18N
        jLabel4.setText("Holder's Name");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(100, 110, 160, 40);

        holder_name_field.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        holder_name_field.setPreferredSize(new java.awt.Dimension(88, 40));
        holder_name_field.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                holder_name_fieldActionPerformed(evt);
            }
        });
        jPanel1.add(holder_name_field);
        holder_name_field.setBounds(340, 110, 320, 40);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 750, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 450, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void holder_name_fieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_holder_name_fieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_holder_name_fieldActionPerformed

    public JPasswordField getConfirm_password_field() {
        return confirm_password_field;
    }

    public JPasswordField getPassword_field() {
        return password_field;
    }

    public JTextField getUsername_field() {
        return username_field;
    }

    public JTextField getHolder_name_field() {
        return holder_name_field;
    }

    
    /**
     * @return 
     */
    public static CreateAccountWindow getInstance() {
        createWindow.setLocationRelativeTo(null);  
        createWindow.setResizable(false);
        return createWindow;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPasswordField confirm_password_field;
    private javax.swing.JButton cretae_button;
    private javax.swing.JTextField holder_name_field;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPasswordField password_field;
    private javax.swing.JTextField username_field;
    // End of variables declaration//GEN-END:variables
}
