/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import controller.navigation_window.LogOutButtonController;
import controller.navigation_window.NewEntryButtonController;
import controller.navigation_window.SearchButtonController;
import controller.navigation_window.WithdrawButtonController;
import javax.swing.JOptionPane;

/**
 *
 * @author Sandu
 */
public class NavigationWindow extends javax.swing.JFrame {

    /**
     * Creates new form NavigationWindow
     */
    public NavigationWindow() {
        super("Dharmapala Maha Vidyala");
        initComponents();
        postInit();
    }

    public void postInit(){
        NewEntryButtonController button_listener = new NewEntryButtonController(this);
        new_entry_button.addActionListener(button_listener);
                
        SearchButtonController searchButtonController = new SearchButtonController(this);
        search_button.addActionListener(searchButtonController);
        
        WithdrawButtonController withdrawButtonController = new WithdrawButtonController(this);
        withdraw_button.addActionListener(withdrawButtonController);
        
        LogOutButtonController logOutButtonController = new LogOutButtonController(this);
        logout_button.addActionListener(logOutButtonController);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        new_entry_button = new javax.swing.JButton();
        search_button = new javax.swing.JButton();
        withdraw_button = new javax.swing.JButton();
        logout_button = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setMinimumSize(new java.awt.Dimension(750, 450));
        jPanel1.setPreferredSize(new java.awt.Dimension(750, 450));
        jPanel1.setLayout(null);

        new_entry_button.setFont(new java.awt.Font("Trajan Pro", 1, 18)); // NOI18N
        new_entry_button.setText("New Entry");
        jPanel1.add(new_entry_button);
        new_entry_button.setBounds(80, 60, 280, 50);

        search_button.setFont(new java.awt.Font("Trajan Pro", 1, 18)); // NOI18N
        search_button.setText("Search Entry");
        jPanel1.add(search_button);
        search_button.setBounds(80, 150, 280, 50);

        withdraw_button.setFont(new java.awt.Font("Trajan Pro", 1, 18)); // NOI18N
        withdraw_button.setText("Withdraw");
        jPanel1.add(withdraw_button);
        withdraw_button.setBounds(80, 240, 280, 50);

        logout_button.setFont(new java.awt.Font("Trajan Pro", 1, 18)); // NOI18N
        logout_button.setText("Log Out");
        logout_button.setPreferredSize(new java.awt.Dimension(115, 50));
        jPanel1.add(logout_button);
        logout_button.setBounds(80, 330, 280, 50);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void start() {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NavigationWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NavigationWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NavigationWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NavigationWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                NavigationWindow navigationWindow = new NavigationWindow();
                navigationWindow.setVisible(true);
                navigationWindow.setLocationRelativeTo(null);
                navigationWindow.setResizable(false);
                 
                navigationWindow.addWindowListener(new java.awt.event.WindowAdapter(){
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent windowEvent) {
                        int showConfirmDialog = JOptionPane.showConfirmDialog(null, 
                                "Do you want to exit","Exit",
                                JOptionPane.YES_NO_OPTION);
                        
                        if(showConfirmDialog == JOptionPane.YES_OPTION){
                            System.exit(0);
                        }
                    }
                });
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton logout_button;
    private javax.swing.JButton new_entry_button;
    private javax.swing.JButton search_button;
    private javax.swing.JButton withdraw_button;
    // End of variables declaration//GEN-END:variables
}
