/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import controller.NewEntryWindow.EnterDataButtonController;
import java.awt.Color;
import java.awt.Font;
import java.awt.event.KeyEvent;
import java.awt.event.KeyListener;
import javax.swing.JComboBox;
import javax.swing.JLabel;
import javax.swing.JTable;
import javax.swing.SwingConstants;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Sandu
 */
public class NewEntryWindow extends javax.swing.JFrame {

    private static final NewEntryWindow newEntryWindow = new NewEntryWindow();
    private int grade_index;
    private int class_index;
    private int operation;
    /**
     * Creates new form NewClassEntryWindow
     */
    private NewEntryWindow() {
        super("Dharmapala Maha Vidyala");
        initComponents();
        jScrollPane1.getViewport().setBackground(Color.WHITE);
        ((JLabel)this.grade_combo_box.getRenderer()).setHorizontalAlignment(SwingConstants.CENTER);
        ((JLabel)this.class_combo_box.getRenderer()).setHorizontalAlignment(SwingConstants.CENTER);
        this.input_data_table.getTableHeader().setFont(new Font("Times New Roman", Font.BOLD, 14));
        init();
        postInit();
    }

    public void init(){
        if(operation == 1){
            this.grade_combo_box.setSelectedIndex(grade_index);
            this.grade_combo_box.setEnabled(false);
            this.class_combo_box.setSelectedIndex(class_index);
            this.class_combo_box.setEnabled(false);
        }
        
        DefaultTableModel tablemodel = (DefaultTableModel) this.input_data_table.getModel();
        input_data_table.addKeyListener(new KeyListener(){

            @Override
            public void keyPressed(KeyEvent e) {
                if(e.getID() == KeyEvent.KEY_PRESSED){
                    if(e.getKeyCode() == KeyEvent.VK_ENTER){
                        tablemodel.setRowCount(tablemodel.getRowCount()+1);
                    }
                }
            }

            @Override
            public void keyTyped(KeyEvent e) {
                
            }

            @Override
            public void keyReleased(KeyEvent e) {
                
            }
        });
    }
    
    public void postInit(){
        EnterDataButtonController button_listener = new EnterDataButtonController(this);
        enter_data_button.addActionListener(button_listener);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        input_data_table = new javax.swing.JTable();
        enter_data_button = new javax.swing.JButton();
        grade_combo_box = new javax.swing.JComboBox();
        class_combo_box = new javax.swing.JComboBox();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1100, 650));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setMinimumSize(new java.awt.Dimension(1100, 650));
        jPanel1.setPreferredSize(new java.awt.Dimension(1100, 650));
        jPanel1.setLayout(null);

        jLabel1.setFont(new java.awt.Font("Trajan Pro", 0, 18)); // NOI18N
        jLabel1.setText("Choose grade");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(30, 30, 160, 30);

        input_data_table.setBackground(new java.awt.Color(230, 227, 227));
        input_data_table.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        input_data_table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null}
            },
            new String [] {
                "No", "Index No", "Student Name", "Receipt No", "Amount"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Float.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        input_data_table.setRowHeight(20);
        jScrollPane1.setViewportView(input_data_table);

        jPanel1.add(jScrollPane1);
        jScrollPane1.setBounds(30, 120, 1020, 370);

        enter_data_button.setFont(new java.awt.Font("Trajan Pro", 0, 18)); // NOI18N
        enter_data_button.setText("Enter Data");
        jPanel1.add(enter_data_button);
        enter_data_button.setBounds(800, 520, 250, 50);

        grade_combo_box.setFont(new java.awt.Font("Trajan Pro", 0, 14)); // NOI18N
        grade_combo_box.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Grade 1", "Grade 2", "Grade 3", "Grade 4", "Grade 5", "Grade 6", "Grade 7", "Grade 8", "Grade 9", "Grade 10", "Grade 11", "Grade 12", "Grade 13" }));
        jPanel1.add(grade_combo_box);
        grade_combo_box.setBounds(30, 60, 140, 30);

        class_combo_box.setFont(new java.awt.Font("Trajan Pro", 0, 14)); // NOI18N
        class_combo_box.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "A", "B", "C", "D", "E", "F", "G", "H", "I", "J", "K", "L", "M", "N", "O", "P", "Q", "R", "S", "T", "U", "V", "W", "X", "Y", "Z" }));
        jPanel1.add(class_combo_box);
        class_combo_box.setBounds(230, 60, 90, 30);

        jLabel5.setFont(new java.awt.Font("Trajan Pro", 0, 18)); // NOI18N
        jLabel5.setText("Choose class");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(210, 30, 150, 30);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public JTable getTable(){
        return input_data_table;
    }

    public JComboBox getClass_combo_box() {
        return class_combo_box;
    }

    public JComboBox getGrade_combo_box() {
        return grade_combo_box;
    }

    public void setGrade_index(int grade_index) {
        this.grade_index = grade_index;
    }

    public void setClass_index(int class_index) {
        this.class_index = class_index;
    }
    
    
    /**
     * @param args the command line arguments
     */
    public static NewEntryWindow getInstance() {
        newEntryWindow.setLocationRelativeTo(null);
        newEntryWindow.setResizable(false);
        return newEntryWindow;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox class_combo_box;
    private javax.swing.JButton enter_data_button;
    private javax.swing.JComboBox grade_combo_box;
    private javax.swing.JTable input_data_table;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
