/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import controller.remove_account_window.RemoveButtonController;
import javax.swing.JTextField;

/**
 *
 * @author Sandu
 */
public class RemoveAccountWindow extends javax.swing.JFrame {

    private static RemoveAccountWindow removeAccountWindow = new RemoveAccountWindow();
    /**
     * Creates new form RemoveAccountWindow
     */
    private RemoveAccountWindow() {
        super("Dharmapala Maha Vidyala");
        initComponents();
        postInit();
    }
    
    private void postInit() {
        RemoveButtonController removeButtonController = new RemoveButtonController(this);
        remove_button.addActionListener(removeButtonController);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        username_field = new javax.swing.JTextField();
        remove_button = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(null);

        jLabel1.setFont(new java.awt.Font("Trajan Pro", 0, 14)); // NOI18N
        jLabel1.setText("User Name");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(90, 120, 130, 40);

        username_field.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jPanel1.add(username_field);
        username_field.setBounds(230, 120, 400, 40);

        remove_button.setFont(new java.awt.Font("Trajan Pro", 0, 18)); // NOI18N
        remove_button.setText("Remove");
        jPanel1.add(remove_button);
        remove_button.setBounds(430, 190, 200, 50);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 733, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 426, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public JTextField getUsername_field() {
        return username_field;
    }

    
    
    /**
     * @return 
     */
    public static RemoveAccountWindow getInstance() {
        removeAccountWindow.setLocationRelativeTo(null);
        removeAccountWindow.setResizable(false);
        return removeAccountWindow;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton remove_button;
    private javax.swing.JTextField username_field;
    // End of variables declaration//GEN-END:variables

    
}
