/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import controller.update_entry_window.UpdateButtonController;
import java.awt.Color;
import java.awt.Font;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Sandu
 */
public class UpdateEntryWindow extends javax.swing.JFrame {

    private static int [] selectedRows;
    private static JTable data_table;
    private static String name;
    /**
     * Creates new form UpdateEntryWindow
     */
    public UpdateEntryWindow() {
        initComponents();
        jScrollPane1.getViewport().setBackground(Color.WHITE);
        init();
        postInit();
    }

    public void init(){        
        this.class_name_field.setText(name);
        this.update_table.getTableHeader().setFont(new Font("Times New Roman", Font.BOLD, 14));
        int row = 0;
        DefaultTableModel tablemodel = (DefaultTableModel) this.update_table.getModel();
        for(int index:selectedRows){
            tablemodel.setRowCount(row+1);
            for(int i=0;i<this.update_table.getColumnCount();i++){
                this.update_table.setValueAt(data_table.getValueAt(index, i), row, i);
            } 
            row++;
        }
    }
    
    public void postInit(){
        UpdateButtonController updateButtonController = new UpdateButtonController(this);
        update_button.addActionListener(updateButtonController);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        update_table = new javax.swing.JTable();
        update_button = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        class_name_field = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(1450, 735));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setMinimumSize(new java.awt.Dimension(1400, 690));
        jPanel1.setPreferredSize(new java.awt.Dimension(1450, 735));
        jPanel1.setLayout(null);

        update_table.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        update_table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "No", "Index No", "Student Name", "Receipt No", "Amount", "Public", "Class", "Sport", "Membership"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Double.class, java.lang.Double.class, java.lang.Double.class, java.lang.Double.class, java.lang.Double.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        update_table.setCellSelectionEnabled(true);
        update_table.setRowHeight(20);
        jScrollPane1.setViewportView(update_table);

        jPanel1.add(jScrollPane1);
        jScrollPane1.setBounds(30, 90, 1300, 470);

        update_button.setFont(new java.awt.Font("Trajan Pro", 1, 18)); // NOI18N
        update_button.setText("Update");
        jPanel1.add(update_button);
        update_button.setBounds(1080, 600, 250, 50);

        jLabel1.setFont(new java.awt.Font("Trajan Pro", 0, 18)); // NOI18N
        jLabel1.setText("Class Name : ");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(30, 30, 140, 30);

        class_name_field.setEditable(false);
        class_name_field.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        class_name_field.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jPanel1.add(class_name_field);
        class_name_field.setBounds(170, 30, 210, 30);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public JTable getData_table() {
        return this.data_table;
    }
    
    public JTable getUpdate_table() {
        return this.update_table;
    }

    public String getClass_name() {
        return name;
    }

    public static int[] getSelectedRows() {
        return selectedRows;
    }

    
    /**
     * @param args the command line arguments
     */
    public static void start(String class_name, int [] rows, JTable data)  {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(UpdateEntryWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(UpdateEntryWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(UpdateEntryWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UpdateEntryWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        selectedRows = rows;
        data_table = data;
        name = class_name;
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                UpdateEntryWindow updateEntryWindow = new UpdateEntryWindow();
                updateEntryWindow.setVisible(true);
                updateEntryWindow.setLocationRelativeTo(null);
                updateEntryWindow.setResizable(false);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField class_name_field;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton update_button;
    private javax.swing.JTable update_table;
    // End of variables declaration//GEN-END:variables
}
