/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import controller.update_account_window.UpdateButtonController;
import javax.swing.JPasswordField;
import javax.swing.JTextField;

/**
 *
 * @author Sandu
 */
public class UpdateAccountWindow extends javax.swing.JFrame {

    private static UpdateAccountWindow updateAccountWindow = new UpdateAccountWindow();
    /**
     * Creates new form UpdateAccountWindow
     */
    private UpdateAccountWindow() {
        super("Dharmapala Maha Vidyala");
        initComponents();
        postInit();
    }

    public void postInit(){
        UpdateButtonController buttonController = new UpdateButtonController(this);
        update_button.addActionListener(buttonController);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        update_button = new javax.swing.JButton();
        new_username_field = new javax.swing.JTextField();
        password_field = new javax.swing.JPasswordField();
        confirm_password_field = new javax.swing.JPasswordField();
        jLabel4 = new javax.swing.JLabel();
        current_username_field = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        setMinimumSize(new java.awt.Dimension(750, 450));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(null);

        jLabel1.setFont(new java.awt.Font("Trajan Pro", 0, 16)); // NOI18N
        jLabel1.setText("New User Name");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(90, 130, 160, 40);

        jLabel2.setFont(new java.awt.Font("Trajan Pro", 0, 16)); // NOI18N
        jLabel2.setText("New Password");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(90, 210, 200, 40);

        jLabel3.setFont(new java.awt.Font("Trajan Pro", 0, 16)); // NOI18N
        jLabel3.setText("Confirm Password");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(90, 290, 210, 40);

        update_button.setFont(new java.awt.Font("Trajan Pro", 0, 18)); // NOI18N
        update_button.setText("Update");
        jPanel1.add(update_button);
        update_button.setBounds(450, 360, 200, 50);

        new_username_field.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jPanel1.add(new_username_field);
        new_username_field.setBounds(320, 130, 330, 40);

        password_field.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jPanel1.add(password_field);
        password_field.setBounds(320, 210, 330, 40);

        confirm_password_field.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jPanel1.add(confirm_password_field);
        confirm_password_field.setBounds(320, 290, 330, 40);

        jLabel4.setFont(new java.awt.Font("Trajan Pro", 0, 16)); // NOI18N
        jLabel4.setText("Current User Name");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(90, 50, 190, 40);

        current_username_field.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jPanel1.add(current_username_field);
        current_username_field.setBounds(320, 50, 330, 40);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 750, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 450, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public JPasswordField getConfirm_password_field() {
        return confirm_password_field;
    }

    public JPasswordField getPassword_field() {
        return password_field;
    }

    public JTextField getNew_username_field() {
        return new_username_field;
    }

    public JTextField getCurrent_username_field() {
        return current_username_field;
    }


    /**
     * @return 
     */
    public static UpdateAccountWindow getInstance() {
        updateAccountWindow.setLocationRelativeTo(null);
        updateAccountWindow.setResizable(false);
        return updateAccountWindow;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPasswordField confirm_password_field;
    private javax.swing.JTextField current_username_field;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField new_username_field;
    private javax.swing.JPasswordField password_field;
    private javax.swing.JButton update_button;
    // End of variables declaration//GEN-END:variables
}
