/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import controller.withdraw_window.ClassComboBoxController;
import controller.withdraw_window.GradeComboBoxController;
import controller.withdraw_window.WithdrawController;
import javax.swing.JButton;
import javax.swing.JComboBox;
import javax.swing.JLabel;
import javax.swing.JTextArea;
import javax.swing.JTextField;
import javax.swing.SwingConstants;

/**
 *
 * @author Sandu
 */
public class WithdrawWindow extends javax.swing.JFrame {

    private static WithdrawWindow withdrawWindow = new WithdrawWindow();
    /**
     * Creates new form WidthrawWindow
     */
    private WithdrawWindow() {
        super("Dharmapala Maha Vidyala");
        initComponents();
        ((JLabel)this.grade_combo_box.getRenderer()).setHorizontalAlignment(SwingConstants.CENTER);
        ((JLabel)this.class_combo_box.getRenderer()).setHorizontalAlignment(SwingConstants.CENTER);
        postInit();
    }

    public void postInit(){
        GradeComboBoxController gradeComboBoxController = new GradeComboBoxController(this);
        grade_combo_box.addActionListener(gradeComboBoxController);
        
        ClassComboBoxController classComboBoxController = new ClassComboBoxController(this);
        class_combo_box.addActionListener(classComboBoxController);
        
        WithdrawController withdrawButtonController = new WithdrawController(this);
        withdrow_button.addActionListener(withdrawButtonController);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        available_field = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        return_field = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        balance_field = new javax.swing.JTextField();
        withdrow_button = new javax.swing.JButton();
        grade_combo_box = new javax.swing.JComboBox();
        class_combo_box = new javax.swing.JComboBox();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        description_area = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setMinimumSize(new java.awt.Dimension(1100, 650));
        jPanel1.setPreferredSize(new java.awt.Dimension(1100, 650));
        jPanel1.setLayout(null);

        jLabel1.setFont(new java.awt.Font("Trajan Pro", 0, 18)); // NOI18N
        jLabel1.setText("Total Available");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(90, 90, 160, 40);

        available_field.setEditable(false);
        available_field.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        available_field.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jPanel1.add(available_field);
        available_field.setBounds(270, 90, 270, 40);

        jLabel2.setFont(new java.awt.Font("Trajan Pro", 0, 18)); // NOI18N
        jLabel2.setText("Return");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(90, 150, 120, 40);

        return_field.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        return_field.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jPanel1.add(return_field);
        return_field.setBounds(270, 150, 270, 40);

        jLabel3.setFont(new java.awt.Font("Trajan Pro", 0, 18)); // NOI18N
        jLabel3.setText("Balance");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(630, 90, 90, 40);

        balance_field.setEditable(false);
        balance_field.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        balance_field.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jPanel1.add(balance_field);
        balance_field.setBounds(740, 90, 270, 40);

        withdrow_button.setFont(new java.awt.Font("Trajan Pro", 0, 18)); // NOI18N
        withdrow_button.setText("Withdraw");
        jPanel1.add(withdrow_button);
        withdrow_button.setBounds(790, 510, 220, 50);

        grade_combo_box.setFont(new java.awt.Font("Trajan Pro", 0, 18)); // NOI18N
        grade_combo_box.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Grade 1", "Grade 2", "Grade 3", "Grade 4", "Grade 5", "Grade 6", "Grade 7", "Grade 8", "Grade 9", "Grade 10", "Grade 11", "Grade 12", "Grade 13" }));
        grade_combo_box.setPreferredSize(new java.awt.Dimension(118, 30));
        jPanel1.add(grade_combo_box);
        grade_combo_box.setBounds(90, 40, 140, 30);

        class_combo_box.setFont(new java.awt.Font("Trajan Pro", 0, 18)); // NOI18N
        class_combo_box.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "A", "B", "C", "D", "E", "F", "G", "H", "I", "J", "K", "L", "M", "N", "O", "P", "Q", "R", "S", "T", "U", "V", "W", "X", "Y", "Z" }));
        class_combo_box.setEnabled(false);
        class_combo_box.setPreferredSize(new java.awt.Dimension(50, 30));
        jPanel1.add(class_combo_box);
        class_combo_box.setBounds(290, 40, 90, 30);

        jLabel4.setFont(new java.awt.Font("Trajan Pro", 0, 18)); // NOI18N
        jLabel4.setText("Description");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(90, 240, 140, 30);

        description_area.setColumns(20);
        description_area.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        description_area.setRows(5);
        jScrollPane1.setViewportView(description_area);

        jPanel1.add(jScrollPane1);
        jScrollPane1.setBounds(90, 290, 600, 270);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public JTextField getBalance_field() {
        return balance_field;
    }

    public JComboBox getGrade_combo_box() {
        return grade_combo_box;
    }

    public JTextField getReturn_field() {
        return return_field;
    }

    public JButton getWithdrow_button() {
        return withdrow_button;
    }

    public JComboBox getClass_combo_box() {
        return class_combo_box;
    }

    public JTextField getAvailable_field() {
        return available_field;
    }

    public JTextArea getDescription_area() {
        return description_area;
    }

    public static WithdrawWindow getInstance() {

        withdrawWindow.setLocationRelativeTo(null);
        withdrawWindow.setResizable(false);
        return withdrawWindow;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField available_field;
    private javax.swing.JTextField balance_field;
    private javax.swing.JComboBox class_combo_box;
    private javax.swing.JTextArea description_area;
    private javax.swing.JComboBox grade_combo_box;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField return_field;
    private javax.swing.JButton withdrow_button;
    // End of variables declaration//GEN-END:variables
}
